name: Maven build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17, 21]
        include:
          - os: ubuntu-latest
            java: 17
            # run PIT mutation test once along with integration tests, jacoco, e2e, coveralls and surefire report plugin generation on ubuntu
            additional-arguments: "surefire-report:report-only -DrepoToken=$COVERALLS_REPO_TOKEN -DpullRequest=${{ github.event.pull_request.number }} coveralls:report -Pintegration-tests org.pitest:pitest-maven:mutationCoverage"
            integration-tests: with PIT and integration tests

    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven ${{ matrix.os }} on Java ${{ matrix.java }} ${{ matrix.integration-tests }}
        run: >
          xvfb-run mvn verify -f com.rosa.angelo.progetto.ast/pom.xml ${{ matrix.additional-arguments }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Archive JUnit Reports
        if: ${{ matrix.java == 17 }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-pit-${{ matrix.java }}-${{ matrix.os }}
          path: |
            **/target/site/jacoco
            **/target/pit-reports
